### PR TITLE
#582 add 2724 for drive

### LINKED ISSUE #582: Add drive motor
**Motivation**

- ...

**What should be realised**

```python
...
```

### PR DESCRIPTION
**Pull request by takayama-27**
**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #582

### CODE REVIEW

**Review by r-yamada1998 — APPROVED** [review]
Looks Good To Me

**Review by r-yamada1998 — APPROVED** [review]
Looks Good To ME

**Review by r-yamada1998 — APPROVED** [review]
Good

**Review by r-yamada1998 — APPROVED** [review]
Good

**Review by takayama-27 — COMMENTED** [review]
test

**Pull request merged**
